Web App/BonfireWebApp/BonfireWebApp/Models/Beacon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace BonfireWebApp.Models
{
    public class Beacon
    {
        [Key]
        [Display(Name="Unique Identifier")]
        public string uuid { get; set; }

        [Required]
        [StringLength(128)]
        [Display(Name="Descriptive Name")]
        public string Name { get; set; }

        [Required]
        [StringLength(64)]
        [Display(Name="Location")]
        public string Location { get; set; }
    }

    public class BeaconDBContext : IDisposable
    {
        public BeaconDBContext()
        {

        }

        public void Dispose()
        {
            //throw new NotImplementedException();
        }

        public List<Beacon> GetAllBeacons()
        {
            List<Beacon> list = new List<Beacon>();

            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand("uspSelectAllBeacons", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    SqlParameter paramResp = new SqlParameter("@response", SqlDbType.Int);
                    paramResp.Direction = ParameterDirection.Output;
                    cmd.Parameters.Add(paramResp);

                    con.Open();
                    var reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {
                        Beacon user = new Beacon();
                        user.uuid = reader["uuid"].ToString();
                        user.Name = reader["Name"].ToString();
                        user.Location = reader["Location"].ToString();
                        list.Add(user);
                    }
                }
            }

            return list;
        }

        public List<string> GetAllBeaconsIds()
        {
            List<string> result = new List<string>();

            List<Beacon> list = GetAllBeacons();

            foreach(Beacon b in list)
            {
                result.Add(b.uuid);
            }

            return result;
        }

        public Beacon GetBeaconById(string uuid)
        {
            Beacon beacon = new Beacon();

            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand("uspSelectBeacon", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    try
                    {
                        cmd.Parameters.Add("@pUuid", SqlDbType.UniqueIdentifier).Value = new Guid(uuid);
                    }
                    catch (SqlException e)
                    {
                        throw e;
                    }

                    SqlParameter paramResp = new SqlParameter("@response", SqlDbType.Int);
                    paramResp.Direction = ParameterDirection.Output;
                    cmd.Parameters.Add(paramResp);

                    con.Open();
                    var reader = cmd.ExecuteReader();

                    while (reader.Read())
                    {
                        beacon.uuid = uuid;
                        beacon.Name = reader["Name"].ToString();
                        beacon.Location = reader["Location"].ToString();
                    }
                }
            }

            if (String.IsNullOrWhiteSpace(beacon.uuid))
                throw new Exception("UUID not in Database.");

            return beacon;
        }

        public bool AddNewBeacon(Beacon beacon)
        {
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand("uspAddBeacon", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.Add("@pUuid", SqlDbType.UniqueIdentifier).Value = new Guid(beacon.uuid);
                    cmd.Parameters.Add("@pName", SqlDbType.VarChar).Value = beacon.Name;
                    cmd.Parameters.Add("@pLocation", SqlDbType.VarChar).Value = beacon.Location;

                    SqlParameter paramResp = new SqlParameter("@response", SqlDbType.Int);
                    paramResp.Direction = ParameterDirection.Output;
                    cmd.Parameters.Add(paramResp);

                    con.Open();
                    cmd.ExecuteNonQuery();

                    return Int32.Parse(paramResp.Value.ToString()) == 1;
                }
            }
        }

        public bool EditBeacon(Beacon beacon)
        {
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand("uspEditBeacon", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.Add("@pUuid", SqlDbType.UniqueIdentifier).Value = new Guid(beacon.uuid);
                    cmd.Parameters.Add("@pName", SqlDbType.VarChar).Value = beacon.Name;
                    cmd.Parameters.Add("@pLocalization", SqlDbType.VarChar).Value = beacon.Location;

                    SqlParameter paramResp = new SqlParameter("@response", SqlDbType.Int);
                    paramResp.Direction = ParameterDirection.Output;
                    cmd.Parameters.Add(paramResp);

                    con.Open();
                    cmd.ExecuteNonQuery();

                    return Int32.Parse(paramResp.Value.ToString()) == 1;
                }
            }
        }

        public bool DeleteBeacon(string uuid)
        {
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand("uspDeleteBeacon", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.Add("@pUuid", SqlDbType.UniqueIdentifier).Value = new Guid(uuid);

                    SqlParameter paramResp = new SqlParameter("@response", SqlDbType.Int);
                    paramResp.Direction = ParameterDirection.Output;
                    cmd.Parameters.Add(paramResp);

                    con.Open();
                    cmd.ExecuteNonQuery();

                    return Int32.Parse(paramResp.Value.ToString()) == 1;
                }
            }
        }
    }
}

Web App/BonfireWebApp/BonfireWebApp/Controllers/BeaconsController.cs
using BonfireWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BonfireWebApp.Controllers
{
    public class BeaconsController : Controller
    {
        // GET: Beacon
        public ActionResult Index()
        {
            if (!IsUserLoggedIn())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            IList<Beacon> list;

            using (BeaconDBContext db = new BeaconDBContext())
            {
                list = db.GetAllBeacons();
            }

            return View(list);
        }

        public ActionResult Edit(string id)
        {
            if (!IsUserLoggedIn())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            Beacon beacon = new Beacon();

            if (!String.IsNullOrWhiteSpace(id))
            {
                using (BeaconDBContext db = new BeaconDBContext())
                {
                    try
                    { 
                        beacon = db.GetBeaconById(id);
                    }
                    catch (Exception e)
                    {
                        return RedirectToAction("Error", "Home", new { id = 0 });
                    }
                }
            }

            return View(beacon);
        }

        [HttpPost]
        public ActionResult Save(Beacon beacon)
        {
            if (!IsUserLoggedIn())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            if (String.IsNullOrWhiteSpace(beacon.uuid))
            {
                ModelState.AddModelError("uuid", "Please fill this field.");
                return View("Edit", beacon);
            }

            try
            {
                new Guid(beacon.uuid);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("uuid", "UUID must have 32 characters, separated by 4 dashes.");
                beacon.uuid = null;
                return View("Edit", beacon);
            }

            if (String.IsNullOrWhiteSpace(beacon.Name))
            {
                ModelState.AddModelError("Name", "Please fill this field.");
                return View("Edit", beacon);
            }

            if (String.IsNullOrWhiteSpace(beacon.Location))
            {
                ModelState.AddModelError("Localization", "Please fill this field.");
                return View("Edit", beacon);
            }

            using (BeaconDBContext db = new BeaconDBContext())
            {
                bool success;

                if (Request.Params["typeofedit"].ToString().Equals("new")) // hiddenfield can be 2 values: new, exists
                {
                    success = db.AddNewBeacon(beacon);
                    return RedirectToAction("Index", new { result = success ? 1 : 0, add = 1 });
                }

                success = db.EditBeacon(beacon);
                return RedirectToAction("Index", new { result = success ? 1 : 0, add = 0 });
            }
        }

        public ActionResult Delete(string id)
        {
            if (!IsUserLoggedIn())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            using (BeaconDBContext db = new BeaconDBContext())
            {
                bool success;

                if (String.IsNullOrWhiteSpace(id))
                {
                    return RedirectToAction("Index", new { result = 0, delete = 1 });
                }

                success = db.DeleteBeacon(id);
                return RedirectToAction("Index", new { result = success ? 1 : 0, delete = 1 });
            }
        }

        private bool IsUserLoggedIn()
        {
            if (Session["UserID"] == null)
                return false;

            using (UserDBContext db = new UserDBContext())
            {
                User user = db.GetUserById(Int32.Parse(Session["UserID"].ToString()));

                if (user.id == 0) // User deleted from DB
                {
                    Session["UserID"] = null;
                    Session["UserName"] = null;
                    Session["UserPrivilege"] = null;
                    return false;
                }

                Session["UserID"] = user.id.ToString();
                Session["UserName"] = user.Name.ToString();
                Session["UserPrivilege"] = user.Privilege ? "1" : "0";
            }

            return true;
        }
    }
}

Web App/BonfireWebApp/BonfireWebApp/Views/Beacons/Edit.cshtml
@model BonfireWebApp.Models.Beacon

@{
    ViewBag.Title = !String.IsNullOrWhiteSpace(Model.uuid) ? "Edit Beacon" : "Add Beacon";
}

<style>
    bigger-form-control {
        min-width:300px;
    }
</style>

@if (!String.IsNullOrWhiteSpace(Model.uuid))
{
    <h2>Edit Existing Beacon</h2>
}
else
{
    <h2>Add New Beacon</h2>
}

@using (Html.BeginForm("Save", "Beacons", FormMethod.Post, new { @data_toggle = "validator" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Hidden("typeofedit", !String.IsNullOrWhiteSpace(Model.uuid) ? "exists" : "new")
        <div class="form-group">
            @Html.LabelFor(model => model.uuid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (!String.IsNullOrWhiteSpace(Model.uuid))
                {
                    @Html.EditorFor(model => model.uuid, new { htmlAttributes = new { @type="uuid", @class = "form-control", @readonly = "true", @required = "true", @style = "min-width:300px" } })
                }
                else
                {
                    @Html.EditorFor(model => model.uuid, new { htmlAttributes = new { @type="uuid", @class = "form-control", @required = "true", @style = "min-width:300px" } })
                }
                @Html.ValidationMessageFor(model => model.uuid, "", new { @class = "text-danger" })
                <div class="help-block with-errors"></div>
            </div>
        </div>

        <div class="form-group has-feedback">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Name, new { @class = "form-control", @required = "true", @style = "min-width:300px", @rows = 4 })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                <div class="help-block with-errors"></div>
            </div>
        </div>

        <div class="form-group has-feedback">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @required = "true", @style = "min-width:300px" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                <div class="help-block with-errors"></div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" name="Save" class="btn btn-default">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web App/BonfireWebApp/BonfireWebApp/Views/Beacons/Index.cshtml
@model IList<BonfireWebApp.Models.Beacon>

@{
    ViewBag.Title = "Beacons";
}

<h2>Beacons</h2>
<br />
@if (Request.Params["result"] != null && Request.Params["add"] != null)
{
    if (Int32.Parse(Request.Params["result"].ToString()) == 1)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            @if (Int32.Parse(Request.Params["add"].ToString()) == 1)
            {
                <p>The new beacon was saved successfully</p>
            }
            else
            {
                <p>The beacon was edited successfully.</p>
            }
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error!</strong> The information could not be saved.
        </div>
    }
    <br />
}
@if (Request.Params["result"] != null && Request.Params["delete"] != null)
{
    if (Int32.Parse(Request.Params["result"].ToString()) == 1)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>Beacon deleted successfully.</p>
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error!</strong> The beacon could not be deleted.
        </div>
    }
    <br />
}

<p>
    <a href="@Url.Action("Edit", "Beacons", new { uuid = "" })"><span class="glyphicon glyphicon-plus"></span>&nbsp; Add new Beacon</a>
</p>
<table id="tableBeacons" class="table table-striped table-bordered table-hover table-responsive" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>UUID</th>
            <th>Descriptive Name</th>
            <th>Location</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.uuid</td>
                <td>@item.Name</td>
                <td>@item.Location</td>
                <td>
                    <a href="@Url.Action("Edit", "Beacons", new { id = item.uuid } )"
                       data-toggle="tooltip" data-placement="top" title="Edit">
                    <span class="glyphicon glyphicon-pencil"></span></a>
                    &nbsp;
                    <a href="#" class="delete-icon" data-toggle="modal" data-target=".delete-modal" data-id="@item.uuid" data-username="@item.Name">
                        <span data-toggle="tooltip" data-placement="top" title="Delete"
                              class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade delete-modal" tabindex="-1" role="dialog" aria-labelledby="deleteModal">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete User</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this beacon?</p>
                <p><strong>Beacon's description:</strong> <span id="nameToDelete"></span></p>
                <p>This action is irreversible!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="buttonConfirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#tableBeacons').DataTable({
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            columnDefs: [
                { orderable: false, targets: 3 }
            ],
            "scrollX": true
        });

        $('[data-toggle="tooltip"]').tooltip({ container: 'body' });
    });

    $('.delete-modal').on('show.bs.modal', function (e) {
        var id = $(e.relatedTarget).attr('data-id');
        var name = $(e.relatedTarget).attr('data-username');
        $(this).find('#nameToDelete').text(name);

        $(buttonConfirmDelete).click(function () {
            window.location = '@Url.Action("Delete", "Beacons")' + '/' + id;
        });
    });
</script>