Web App/BonfireWebApp/BonfireWebApp/Controllers/ManagementController.cs
using BonfireWebApp.Helpers;
using BonfireWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BonfireWebApp.Controllers
{
    public class ManagementController : Controller
    {
        // GET: Management
        public ActionResult Index()
        {
            if (!IsUserLoggedIn())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            if (!IsUserAdmin())
                return RedirectToAction("Index", "Contents");

            IList<User> list;

            using(UserDBContext db = new UserDBContext())
            {
                list = db.GetAllUsers();
            }

            return View(list);
        }
        
        public ActionResult Edit(int id)
        {
            if (!IsUserLoggedIn())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            if (!IsUserAdmin())
                return RedirectToAction("Index", "Contents");

            User user = new User();

            if (id < 0)
                return RedirectToAction("Error", "Home", new { id = 0 });

            if (id > 0)
            {
                using (UserDBContext db = new UserDBContext())
                {
                    user = db.GetUserById(id);

                    if (user.id == 0)
                        return RedirectToAction("Error", "Home", new { id = 0 });

                    return View(user);
                }
            }
            
            return View(user);
        }

        [HttpPost]
        public ActionResult Save(User user)
        {
            if (!IsUserLoggedIn() || !IsUserAdmin())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            if (user.Password != null)
            if (user.Password.Length < 6)
            {
                ModelState.AddModelError("Password", "Password must be, at least, 6 characters long.");
                return View(user);
            }

            if (!Validations.IsValidEmail(user.Email))
            {
                ModelState.AddModelError("Email", "Email has an invalid format.");
                return View(user);
            }

            using (UserDBContext db = new UserDBContext())
            {
                bool success;
                
                if (user.id <= 0) {
                    success = db.AddNewUser(user);
                    return RedirectToAction("Index", new { result = success ? 1 : 0 , add = 1 });
                }

                success = db.EditUser(user);
                if (success && user.id == Int32.Parse(Session["UserID"].ToString()))
                {
                    Session["UserName"] = user.Name;
                    Session["UserPrivilege"] = user.Privilege ? "1" : "0";
                }
                return RedirectToAction("Index", new { result = success ? 1 : 0, add = 0 });
            }
        }

        public ActionResult Delete(int id)
        {
            if (!IsUserLoggedIn() || !IsUserAdmin())
            {
                TempData["RedirectMessage"] = "Access denied. Please login.";
                return RedirectToAction("Index", "Home");
            }

            if (Int32.Parse(Session["UserID"].ToString()) == id)
            {
                return RedirectToAction("Index", new { result = 0, delete = 1 });
            }

            using (UserDBContext db = new UserDBContext())
            {
                bool success;

                if (id <= 0)
                {
                    return RedirectToAction("Index", new { result = 0, delete = 1 });
                }

                success = db.DeleteUser(id);
                return RedirectToAction("Index", new { result = success ? 1 : 0, delete = 1 });
            }
        }

        private bool IsUserLoggedIn()
        {
            if (Session["UserID"] == null)
                return false;

            using (UserDBContext db = new UserDBContext())
            {
                User user = db.GetUserById(Int32.Parse(Session["UserID"].ToString()));

                if (user.id == 0) // User deleted from DB
                {
                    Session["UserID"] = null;
                    Session["UserName"] = null;
                    Session["UserPrivilege"] = null;
                    return false;
                }

                Session["UserID"] = user.id.ToString();
                Session["UserName"] = user.Name.ToString();
                Session["UserPrivilege"] = user.Privilege ? "1" : "0";
            }

            return true;
        }

        private bool IsUserAdmin()
        {
            if (Session["UserPrivilege"] != null)
            {
                if (Session["UserPrivilege"].ToString().Equals("1"))
                    return true;
            }
            return false;
        }
    }
}

Web App/BonfireWebApp/BonfireWebApp/Views/Management/Edit.cshtml
@model BonfireWebApp.Models.User

@{
    ViewBag.Title = Model.id > 0 ? "Edit User" : "Add User";
}

@if (Model.id > 0) {
    <h2>Edit Existing User</h2>
}
else { 
    <h2>Add New User</h2>
}

@using (Html.BeginForm("Save", "Management", FormMethod.Post, new { @data_toggle = "validator" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(m => m.id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group has-feedback">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = true } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                <div class="help-block with-errors"></div>
            </div>
        </div>

        <div class="form-group has-feedback">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "email", @required = true } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                <div class="help-block with-errors"></div>
            </div>
        </div>
        
        <div class="form-group has-feedback">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.id > 0)
                {
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @type = "password", @data_minlength = 6 })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    <div class="help-block">Minimum of 6 characters. Leave blank to keep password unchanged.</div>
                }
                else
                {
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @type = "password", @data_minlength = 6, @required = true })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    <div class="help-block">Minimum of 6 characters.</div>
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Privilege, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Privilege)
                    @Html.ValidationMessageFor(model => model.Privilege, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" name="Save" class="btn btn-default">Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web App/BonfireWebApp/BonfireWebApp/Views/Management/Index.cshtml
@model IList<BonfireWebApp.Models.User>

@{
    ViewBag.Title = "Management";
}

<h2>Managers</h2>
<br/>
@if (Request.Params["result"] != null && Request.Params["add"] != null) { 
    if (Int32.Parse(Request.Params["result"].ToString()) == 1)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            @if (Int32.Parse(Request.Params["add"].ToString()) == 1)
            {
                <p>The new user was saved successfully</p>
            }
            else{
                <p>The user was edited successfully.</p>
            }
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error!</strong> The information could not be saved.
        </div>
    }
    <br />
}
@if (Request.Params["result"] != null && Request.Params["delete"] != null)
{
    if (Int32.Parse(Request.Params["result"].ToString()) == 1)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>User deleted successfully.</p>
        </div>
    }
    else
    {
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error!</strong> The user could not be deleted.
        </div>
    }
    <br />
}

<p>
<a href="@Url.Action("Edit", "Management", new { id = 0 })"><span class="glyphicon glyphicon-plus"></span>&nbsp; Add new Manager</a>
</p>
<table id="tableUsers" class="table table-striped table-bordered table-hover table-responsive" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Administrator</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@(item.Privilege ? "Yes" : "No")</td>
                <td>
                    <a href="@Url.Action("Edit", "Management", new { id = item.id } )"
                       data-toggle="tooltip" data-placement="top" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
                    &nbsp;
                    @if(Session["UserID"].ToString() != item.id.ToString()) { 
                        <a href="#" class="delete-icon" data-toggle="modal" data-target=".delete-modal" data-id="@item.id" data-username="@item.Name">
                            <span data-toggle="tooltip" data-placement="top" title="Delete"
                                  class="glyphicon glyphicon-trash"></span></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade delete-modal" tabindex="-1" role="dialog" aria-labelledby="deleteModal">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete User</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete user <strong><span id="nameToDelete"></span></strong>?</p>
                <p>This action is irreversible!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="buttonConfirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#tableUsers').DataTable({
            "scrollX": true,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            columnDefs: [
                { orderable: false, targets: 4 }
            ]
        });

        $('[data-toggle="tooltip"]').tooltip({ container: 'body' });
    });

    $('.delete-modal').on('show.bs.modal', function (e) {
        var id = $(e.relatedTarget).attr('data-id');
        var name = $(e.relatedTarget).attr('data-username');
        $(this).find('#nameToDelete').text(name);

        $(buttonConfirmDelete).click(function () {
            window.location = '@Url.Action("Delete", "Management")' + '/' + id;
        });
    });
</script>